add run.py
idreamshen/tenement pull request #1
Opened 2017-01-31 15:54 UTC by jaymiejjj

新增run.py 使用python脚本来运行scrapy框架中的多个spider，但是需要python的版本为3.X 不然会报错

ps：我注释掉了AnjukeSpider这个spider，有点问题。没排查出来，其余几个爬虫都没问题。

2017-01-31 17:00 UTC, jaymiejjj commented
新增 document项目说明文档，老哥你后续再改下

2017-02-01 12:39 UTC, idreamshen commented
@jaymiejjj 把PR标题修正。标题用中文就行。另外这种场合不要用“老哥”这样的词汇。

2017-02-03 03:54 UTC, idreamshen requested changes

2017-02-03 03:54 UTC, idreamshen commented on README.md
> +5. `python run.py` 执行一键爬虫 *python版本需要为python3*
@jaymiejjj 这里第 5 点和第 4 点功能其实重复。你应当修改第 4 点，说明有两种执行方式。

2017-02-03 06:50 UTC, idreamshen requested changes

2017-02-03 06:50 UTC, idreamshen commented on run.py
> +#使用scrapy api 在一个进程中同时运行多个spider
文件头增加一行
#!/usr/bin/env python3

-----
另外建议将 run.py 转换为可执行文件：`chmod +x run.py`
这样启动命令可改为`./run.py`，而不用`python3 run.py`

2017-02-03 08:04 UTC, jaymiejjj commented
已根据review修改README.md与run.py文件

2017-02-03 08:09 UTC, idreamshen approved these changes

2017-02-03 08:10 UTC, merged